# Generated by Django 3.0.6 on 2020-05-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('service', models.CharField(max_length=50)),
                ('sales_price', models.IntegerField()),
                ('percent_charged', models.IntegerField()),
                ('payment_method', models.IntegerField()),
                ('agent', models.CharField(max_length=60)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
