# Generated by Django 3.0.6 on 2020-05-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='image',
            field=models.ImageField(null=True, upload_to='properties/images'),
        ),
    ]
