# Generated by Django 3.0.6 on 2020-05-06 03:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_properties_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=50)),
                ('last', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('contact', models.IntegerField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='properties',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
