# Generated by Django 3.0.6 on 2020-05-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200505_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='properties',
            name='property_id',
            field=models.IntegerField(null=True),
        ),
    ]
