# Generated by Django 3.0.6 on 2020-05-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200506_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='contact',
            field=models.BigIntegerField(),
        ),
    ]
