# Generated by Django 3.0.6 on 2020-05-06 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_property_type_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Service',
            new_name='service',
        ),
    ]
