# Generated by Django 3.0.6 on 2020-05-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20200506_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='property_type',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
