# Generated by Django 3.0.6 on 2020-05-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_transaction_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_method',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
