# Generated by Django 3.0.6 on 2020-05-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_transaction_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='charge',
            field=models.IntegerField(null=True),
        ),
    ]
