# Generated by Django 3.0.6 on 2020-05-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_transaction_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='geolocation',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
