# Generated by Django 3.0.6 on 2020-05-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_properties_geolocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='property_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
