# Generated by Django 3.0.6 on 2020-05-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200509_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='location',
            new_name='electorial_area',
        ),
        migrations.AddField(
            model_name='properties',
            name='sub_area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
