# Generated by Django 3.0.6 on 2020-05-10 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='agent',
            field=models.CharField(default='Name', max_length=50),
            preserve_default=False,
        ),
    ]
