# Generated by Django 3.0.6 on 2020-05-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_auto_20200510_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='transaction_ref_no',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
