# Generated by Django 3.0.6 on 2020-05-14 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_accounts_transaction_ref_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('business_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post_Ref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_item', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('post_ref', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accounts',
            name='transaction_ref_no',
            field=models.IntegerField(unique=True),
        ),
    ]
