# Generated by Django 3.0.6 on 2020-05-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_auto_20200514_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='business',
            field=models.IntegerField(null=True),
        ),
    ]
