# Generated by Django 3.0.6 on 2020-05-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_accounts_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='comment',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
