# Generated by Django 3.0.6 on 2020-05-15 20:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_accounts_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='start_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='business',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
