# Generated by Django 3.0.6 on 2020-05-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0027_auto_20200515_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Closed', 'Close')], max_length=20, null=True),
        ),
    ]
