# Generated by Django 3.0.6 on 2020-05-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_auto_20200516_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='usd_equi',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='usd_rate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
