# Generated by Django 3.0.6 on 2020-08-09 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_auto_20200516_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('date_of_request', models.DateField()),
                ('service', models.CharField(max_length=50)),
                ('service_area', models.CharField(max_length=50)),
                ('type_of_property', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('willing_to_pay', models.BigIntegerField()),
                ('willing_to_take', models.BigIntegerField()),
                ('price_per_month', models.BigIntegerField()),
                ('contact', models.BigIntegerField()),
                ('is_married', models.BooleanField(default=False)),
                ('number_seeking_rent', models.IntegerField()),
                ('availability_of_water', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_shared_meter', models.BooleanField(default=False)),
                ('years_in_advance', models.IntegerField()),
                ('tenant_prefered', models.CharField(max_length=200)),
                ('deal_breaker', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('added_by', models.CharField(max_length=200)),
                ('task_owner', models.CharField(max_length=200)),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
                ('complete_by', models.DateField()),
            ],
        ),
    ]
