# Generated by Django 3.0.6 on 2020-08-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_properties_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='handler',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
