# Generated by Django 3.0.6 on 2020-08-19 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_properties_handler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='image',
        ),
    ]
